### ISSUE TITLE
使用ssdb4j连redis报错

### ISSUE THREAD

**Issue by yeyincai** [nutzam/ssdb4j#32]
背景：ssdb目前不维护，将数据迁移到云厂商的redis，不改客户端代码
redis版本：4.0
ssdb4j版本：1.0
使用简单的set命令 
原来的代码是连ssdb，现在改p端口连到redis
commentSsdb = SSDBs.pool("172.19.6.105", 6379, 1000, config);
try {
     commentSsdb.set(key, value).check();
 } catch (SSDBException e) {
            e.printStackTrace();
}
报的错误：
org.nutz.ssdb4j.spi.SSDBException: org.nutz.ssdb4j.spi.SSDBException: protocol error. unexpect byte=45
	at org.nutz.ssdb4j.impl.AbstractIoSSDBStream.whenError(AbstractIoSSDBStream.java:38)
	at org.nutz.ssdb4j.impl.SocketSSDBStream.whenError(SocketSSDBStream.java:47)
	at org.nutz.ssdb4j.impl.AbstractIoSSDBStream.req(AbstractIoSSDBStream.java:27)
	at org.nutz.ssdb4j.pool.SocketSSDBStreamFactory.validateObject(SocketSSDBStreamFactory.java:26)
	at org.nutz.ssdb4j.pool.SocketSSDBStreamFactory.validateObject(SocketSSDBStreamFactory.java:8)
	at org.apache.commons.pool.impl.GenericObjectPool.borrowObject(GenericObjectPool.java:1205)
	at org.nutz.ssdb4j.pool.PoolSSDBStream.req(PoolSSDBStream.java:32)
	at org.nutz.ssdb4j.impl.SimpleClient.req(SimpleClient.java:47)
	at org.nutz.ssdb4j.impl.SimpleClient.set(SimpleClient.java:82)
	at com.test.SSDBTest.set(SSDBTest.java:46)
	at com.test.SSDBTest.main(SSDBTest.java:29)
Caused by: org.nutz.ssdb4j.spi.SSDBException: protocol error. unexpect byte=45
	at org.nutz.ssdb4j.SSDBs.readBlock(SSDBs.java:106)
	at org.nutz.ssdb4j.SSDBs.readResp(SSDBs.java:177)
	at org.nutz.ssdb4j.impl.AbstractIoSSDBStream.req(AbstractIoSSDBStream.java:23)
	... 8 more
为啥ssdb4j不支持redis呢？

**Comment by wendal** [comment]
因为没做兼容.
